services:
  - type: web
    name: research-app
    runtime: python
    region: oregon
    plan: free
    
    # Install setuptools FIRST to avoid import errors
    buildCommand: |
      python --version
      pip install --upgrade pip
      pip install setuptools wheel
      pip install -r requirements.txt
    
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    
    envVars:
      # Force Python 3.12 to avoid compatibility issues
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PIP_NO_CACHE_DIR
        value: 1
    
    healthCheckPath: /health
    autoDeploy: true
