services:
  - type: web
    name: research-app
    runtime: python
    region: oregon  # or your preferred region
    plan: free  # or 'starter' for paid plan
    
    buildCommand: |
      echo "==> Attempting standard build..."
      chmod +x build.sh && ./build.sh || {
        echo "==> Standard build failed, trying with constraints..."
        pip install --upgrade pip setuptools wheel
        pip install -r requirements-with-constraints.txt -c constraints.txt
      }
    
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PIP_NO_CACHE_DIR
        value: 1
      - key: PIP_DISABLE_PIP_VERSION_CHECK
        value: 1
      
      # Add your environment variables here
      # - key: DATABASE_URL
      #   fromDatabase:
      #     name: your-db-name
      #     property: connectionString
      
      # - key: SECRET_KEY
      #   generateValue: true
    
    healthCheckPath: /health
    
    autoDeploy: true  # Auto-deploy on git push

# Uncomment if you need a database
# databases:
#   - name: your-db-name
#     plan: free
#     databaseName: research_db
#     user: dbuser
